# Generated by Django 4.2.7 on 2023-11-13 07:55

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Film",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                ("original_title", models.CharField(max_length=200)),
                ("original_title_romanised", models.CharField(max_length=200)),
                ("image", models.URLField(blank=True, null=True)),
                ("banner", models.URLField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("director", models.CharField(max_length=200)),
                ("producer", models.CharField(max_length=200)),
                ("release_date", models.DateField(verbose_name="released on")),
                ("running_time", models.PositiveSmallIntegerField()),
                ("rt_score", models.PositiveSmallIntegerField()),
            ],
            options={
                "verbose_name": "Film",
                "verbose_name_plural": "Films",
            },
        ),
        migrations.CreateModel(
            name="Specie",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("classification", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="People",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("age", models.CharField(max_length=200)),
                ("gender", models.CharField(choices=[("1", "Male"), ("2", "Female"), ("3", "Otther")], max_length=2)),
                ("eye_color", models.CharField(max_length=200)),
                ("hair_color", models.CharField(max_length=200)),
                (
                    "films",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="people",
                        related_query_name="people",
                        to="content.film",
                    ),
                ),
                (
                    "specie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specie",
                        related_query_name="specie",
                        to="content.specie",
                    ),
                ),
            ],
        ),
    ]
